/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author Com
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HospitalDirectory hospitalDirectory;
    private DoctorDirectory doctorDirectory;
    private PatientDirectory patientDirectory;
    private EncounterHistory encounterHistory;

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,HospitalDirectory hospitalDirectory,DoctorDirectory doctorDirectory, PatientDirectory patientDirectory, EncounterHistory encounterHistory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.hospitalDirectory = hospitalDirectory;
        this.doctorDirectory = doctorDirectory;
        this.patientDirectory = patientDirectory;
        this.encounterHistory = encounterHistory;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnModifyHospitals = new javax.swing.JButton();
        btnModifyDoctors = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 600));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("System Administration Portal");

        btnModifyHospitals.setText("Modify Hospitals");
        btnModifyHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyHospitalsActionPerformed(evt);
            }
        });

        btnModifyDoctors.setText("Modify Doctors");
        btnModifyDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModifyHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(71, 71, 71)
                .addComponent(btnModifyHospitals)
                .addGap(18, 18, 18)
                .addComponent(btnModifyDoctors)
                .addContainerGap(415, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyHospitalsActionPerformed
        // TODO add your handling code here:
        ModifyHospitalsJPanel mhjp = new ModifyHospitalsJPanel(userProcessContainer,hospitalDirectory);
        userProcessContainer.add("ModifyHospitalsJPanel",mhjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModifyHospitalsActionPerformed

    private void btnModifyDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyDoctorsActionPerformed
        // TODO add your handling code here:
        ModifyDoctorsJPanel mdjp = new ModifyDoctorsJPanel(userProcessContainer,doctorDirectory,hospitalDirectory);
        userProcessContainer.add("ModifyDoctorsJPanel",mdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModifyDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifyDoctors;
    private javax.swing.JButton btnModifyHospitals;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
